# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 오승민
title: Student
email: peoplesoft1004@gmail.com
Blog: https://velog.io/@osm_cloud

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: osm-cloud
instagram_username: oseungmin9436

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  저는 Python, AWS, Terraform, C를 주로 사용하며 AWS를 활용한 백엔드 플랫폼 인프라 구축에 집중해 왔습니다. <br>
  쉽고 빠르게 인프라를 생성해야 한다는 생각에 Terraform과 AWS CloudFormation을 활용해 MySQL 서버를 구축하고, Code series를 사용해 자동화된 인프라를 구축한 경험이 있습니다. <br>
  시스템 관리뿐만 아니라 소프트웨어 및 웹 애플리케이션을 만드는 데에도 익숙합니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Java, Python, C
          * Spring Boot, AWS Amplify
          * Gradle, Maven
          * Visual Studio Code
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * MySQL, MariaDB, PostgreSQL
          * GitHub Actions, AWS Code Series, ArgoCD
          * Terraform, CloudFormation
          * Nginx, APM(Apache, Php, Mysql)
          * Linux (CentOS)
      - layout: left
        title: AWS Services
        description: | # this will include new lines to allow paragraphs
          * RDS, DynamoDB, ElasticCache (Redis), DocumentDB
          * Kinesis, Glue, Athena, Redshift, OpenSearch
          * EC2, Lambda
          * VPC, CloudFront, API Gateway, Route53, Client VPN
          * ECR, ECS, EKS
          * AppFlow, EventBridge, SQS
          * IAM, WAF, AWS KMS, ACM, Secrets Manager, Cognito
          * DMS
          * CloudWatch, AWS Config, CloudTrail, Systems Manager
          * EFS, S3, Backup

  - title: Education
    layout: list
    content:
      - layout: left
        title: Cloud Computing
        caption: 2023 - 2024
        sub_title: 한국산업인력공단이 주최하는 기능경기대회를 목적으로 개설된 동아리 
        description: | 
          * Public Cloud에서 제공하는 솔루션을 이용하여 IT 인프라를 설계 및 구현하는 수준을 요구
          * 2024 전국기능경기대회 <mark>우수상</mark>
          * 2024 대전지방기능경기대회 <mark>금매달</mark>
          * 2023 대전지방기능경기대회 <mark>장려상</mark>
      - layout: left
        title: Cloud Computing Study
        caption: 2023
        sub_title: AWS 클라우드 교육
        description: | 
          * 기능경기대회를 목적으로 하는 학생들을 대상으로 한 교육
          * 네트워킹/보안
          * Serverless
          * Container
          * CI/CD
          * Data Pipeline
          * Web Service Infra
          * Data Infra
      - layout: left
        title: 계룡디지텍고등학교 정보통신과
        caption: 2022 - 2025
        sub_title: 정보통신 특성화 고등학교
        description: | 
          * 2023 교내 전공연구회 <mark>1위</mark>

  - title: Certificate
    layout: text
    content: |
      - 2024 정보처리기능사

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag