# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 오승민
title: Cloud Engineer
email: peoplesoft1004@gmail.com
website: https://velog.io/@osm_cloud

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: osm-cloud
instagram_username: oseungmin9436

# About Section
about_profile_image: images/profiles.jpg
about_content: | # this will include new lines to allow paragraphs
  저는 Python, AWS, Terraform, C를 주로 사용하며 AWS를 활용한 백엔드 플랫폼 인프라 구축에 집중해 왔습니다. <br>
  쉽고 빠르게 인프라를 생성해야 한다는 생각에 Terraform과 AWS CloudFormation을 활용해 MySQL 서버를 운영하고, GitHub Actions를 사용해 자동화된 인프라를 운영한 경험이 있습니다. <br>
  시스템 관리뿐만 아니라 소프트웨어 및 웹 애플리케이션을 만드는 데에도 익숙합니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Java, Python, C
          * Spring Boot, AWS Amplify
          * Gradle, Maven
          * Visual Studio Code
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * MySQL, MariaDB, PostgreSQL
          * GitHub Actions, AWS Code Series, ArgoCD
          * Terraform, CloudFormation
          * Nginx, Apache
          * Linux (CentOS)
      - layout: left
        title: AWS Services
        description: | # this will include new lines to allow paragraphs
          * RDS, DynamoDB, ElasticCache (Redis), DocumentDB
          * Kinesis, Glue, Athena, Redshift, OpenSearch
          * EC2, Lambda
          * VPC, CloudFront, API Gateway, Route53, Client VPN
          * ECR, ECS, EKS
          * AppFlow, EventBridge, SQS
          * IAM, WAF, AWS KMS, ACM, Secrets Manager, Cognito
          * DMS
          * CloudWatch, AWS Config, CloudTrail, Systems Manager
          * EFS, S3, Backup

  - title: Education
    layout: list
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        description: | 
          During my time at Harvard, I learned key skills like teamwork and working to tight deadlines, which I have carried throughout my career. I also balanced my studies with extracurricular activities, such as being a member of the *Harvard Mountaineering Club*, where I held roles like *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering, some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag